apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: k8s-debug
  name: k8s-debug
  namespace: k8s-debug
spec:
  rules:
    - host: @@HOSTNAME@@
      http:
        paths:
          - backend:
              service:
                name: k8s-debug
                port:
                    number: 80
            path: /
            pathType: Prefix
